# Generated by Django 3.2.9 on 2021-12-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='work',
            name='preview',
            field=models.ImageField(blank=True, upload_to='blog/'),
        ),
    ]
