# Generated by Django 3.2.9 on 2021-12-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='testimonial/')),
                ('designation', models.CharField(max_length=30)),
                ('comment', models.TextField()),
            ],
        ),
    ]
